#!/usr/bin/env bash
set -euo pipefail

export DATA_SOURCE=${DATA_SOURCE:-franka_nut_assembly_code_env}
export MODEL_PATH=${MODEL_PATH:-Qwen/Qwen2.5-Coder-1.5B-Instruct}
export DATA_ROOT=${DATA_ROOT:-$HOME/data/capx/nut_assembly_prompt_only}
export GROUP_SIZE=${GROUP_SIZE:-8}
export TRAIN_DATASET_SIZE=${TRAIN_DATASET_SIZE:-64}
export VAL_DATASET_SIZE=${VAL_DATASET_SIZE:-64}
export TRAIN_BATCH_SIZE=${TRAIN_BATCH_SIZE:-8}
export VAL_BATCH_SIZE=${VAL_BATCH_SIZE:-16}
export PPO_MINI_BATCH_SIZE=${PPO_MINI_BATCH_SIZE:-8}
export PPO_MICRO_BATCH_SIZE=${PPO_MICRO_BATCH_SIZE:-2}
export LOG_PROB_MICRO_BATCH_SIZE=${LOG_PROB_MICRO_BATCH_SIZE:-4}
export ROLLOUT_WORKERS=${ROLLOUT_WORKERS:-4}
export GPU_MEMORY_UTILIZATION=${GPU_MEMORY_UTILIZATION:-0.4}
export MAX_NUM_SEQS=${MAX_NUM_SEQS:-16}
export MAX_MODEL_LEN=${MAX_MODEL_LEN:-2048}
export MAX_NUM_BATCHED_TOKENS=${MAX_NUM_BATCHED_TOKENS:-4096}
export TOTAL_EPOCHS=${TOTAL_EPOCHS:-20}
export SAVE_FREQ=${SAVE_FREQ:-1}
export TEST_FREQ=${TEST_FREQ:-1}
export TRAINER_LOGGER=${TRAINER_LOGGER:-console}
export LORA_RANK=${LORA_RANK:-32}
export LORA_ALPHA=${LORA_ALPHA:-32}
export GRADIENT_CHECKPOINTING=${GRADIENT_CHECKPOINTING:-true}
export ACTOR_PARAM_OFFLOAD=${ACTOR_PARAM_OFFLOAD:-true}
export ACTOR_OPTIMIZER_OFFLOAD=${ACTOR_OPTIMIZER_OFFLOAD:-true}
export REF_PARAM_OFFLOAD=${REF_PARAM_OFFLOAD:-true}
export ASYNC_REWARD=${ASYNC_REWARD:-false}

exec bash "$(dirname "$0")/train_franka_grpo.sh"
